# https://github.com/alacritty/alacritty-theme
# import = [
#   "~/.config/alacritty/themes/themes/alabaster.toml"
# ]

[font]
size = 12.0
normal = {family = "JetBrains Mono", style = "Regular"}

[window]
dimensions = {columns = 130, lines = 46}
opacity = 0.9999

[env]
TERM = "xterm-256color"
