# https://github.com/alacritty/alacritty-theme
import = [
    "~/.config/alacritty/themes/themes/alabaster.toml"
]

[font]
size = 15.0
normal = {"family" = "JetBrains Mono"}

[window]
dimensions = {columns = 100, lines = 35}
