" Generated by vim-plug
" Wed Aug 10 00:08:49 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['awesome-vim-colorschemes'].commit = '9f96bbdef5cb19daf58449f0fbb597af6fc4c2eb'
silent! let g:plugs['cmp-buffer'].commit = '62fc67a2b0205136bc3e312664624ba2ab4a9323'
silent! let g:plugs['cmp-cmdline'].commit = '9c0e331fe78cab7ede1c051c065ee2fc3cf9432e'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'affe808a5c56b71630f17aa7c38e15c59fd648a8'
silent! let g:plugs['cmp-path'].commit = '447c87cdd6e6d6a1d2488b1d43108bfa217f56e1'
silent! let g:plugs['cmp-snippy'].commit = '9af1635fe40385ffa3dabf322039cb5ae1fd7d35'
silent! let g:plugs['fzf'].commit = '4993d19466d5f3ac127de5c0c461cde7ef1894d7'
silent! let g:plugs['fzf.vim'].commit = 'c491d702b76c6b4918abb80be3cfb57d1b618ffa'
silent! let g:plugs['gitsigns.nvim'].commit = '9c3ca027661136a618c82275427746e481c84a4e'
silent! let g:plugs['nerdtree'].commit = 'fc85a6f07c2cd694be93496ffad75be126240068'
silent! let g:plugs['nerdtree-git-plugin'].commit = 'e1fe727127a813095854a5b063c15e955a77eafb'
silent! let g:plugs['nvim-cmp'].commit = '706371f1300e7c0acb98b346f80dad2dd9b5f679'
silent! let g:plugs['nvim-lspconfig'].commit = 'da7461b596d70fa47b50bf3a7acfaef94c47727d'
silent! let g:plugs['nvim-metals'].commit = '9b9fad5fcdf725c07c7c549064fb0347d26770dd'
silent! let g:plugs['nvim-snippy'].commit = '1860215584d4835d87f75896f07007b3b3c06df4'
silent! let g:plugs['nvim-treesitter'].commit = 'e9ab0341394b41ac9fbd197b0a6ceaff3c4d9e51'
silent! let g:plugs['plenary.nvim'].commit = '31807eef4ed574854b8a53ae40ea3292033a78ea'
silent! let g:plugs['toggleterm.nvim'].commit = '623664233bbe305bf7c86060b95670bb1575534d'
silent! let g:plugs['vim-airline'].commit = '61042e35024a133bb5af42850d3852d20ebcc4e1'
silent! let g:plugs['vim-airline-themes'].commit = '55bad92d246a31e3425dfaf16b7eec657eab1fad'
silent! let g:plugs['vim-commentary'].commit = '3654775824337f466109f00eaf6759760f65be34'
silent! let g:plugs['vim-fugitive'].commit = '66a921bbe38bea19f6b581c8a56d5a8a41209e35'
silent! let g:plugs['vim-lua-format'].commit = 'cb07a86f665bd552b4e103f99dd68f97b49bd045'

PlugUpdate!

